---
application:
  name: "vcplaybot"
  project: "Musicbot patrici"
  organization: "QoveryCommunity"
routers:
- name: "main-vcplaybot"
  routes:
  - application_name: "vcplaybot"
    paths:
    - "/*"
