---
application:
  name: "vcplaybotop"
  project: "Musicbotpart2"
  organization: "QoveryCommunity"
routers:
- name: "main-vcplaybotop"
  routes:
  - application_name: "vcplaybotop"
    paths:
    - "/*"
